name: null
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#020202'
    - '#010303'
    - '#020202'
    - '#020202'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
