name: null
favicon: null
layout_spectrum: 0.25482
typography_spectrum: 0.75038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0626'
    - '#c5c8c7'
    - '#fd5366'
    - '#ff7d7e'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose:
  - name: shares
    item: null
    url: null
