name: null
favicon: null
layout_spectrum: 0.25482
typography_spectrum: 0.75038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8f8f8f'
    - '#bfbfbf'
    - '#414141'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose:
  - name: shares
    item: null
    url: null
